---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  size:
    name: Size
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Size
        id: size
        uses: mattdowdell/pr-sizer@e523aba6b9ee5306cd9c69cb08fd59a893e399ca # v0.3.0

  checks:
    name: Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      # TODO: install just
      # TODO: install bingo
      # TODO: run: just checks

  lint:
    name: Lint
    needs:
      - checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'

      - name: Lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          args: --timeout=10m
          # TODO: specifiy version

  unit:
    name: Unit test
    needs:
      - checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'

      - name: Install Just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0

      - name: Unit test
        run: just unit

    # TODO: report coverage to PR
    # maybe gwatts/go-coverage-action?

  # scan:
  #   name: Scan
  #   if: |
  #     always() &&
  #     (needs.checks.result == 'success' || needs.checks.result == 'skipped')
  #   needs:
  #     - checks
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  #       with:
  #         persist-credentials: false

  #     - name: Install Go
  #       uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
  #       with:
  #         go-version-file: 'go.mod'

  #     - name: Install Just
  #       uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0

  #     # required for trivy to find licenses
  #     # see https://trivy.dev/latest/docs/coverage/language/golang/#license
  #     - name: Populate Go mod cache
  #       run: just tidy-go

  #     - name: Run trivy
  #       uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
  #       with:
  #         scan-type: fs
  #         trivy-config: trivy.yaml

  #     # TODO: publish to github for default branch builds?
  #     # https://github.com/actions/starter-workflows/blob/main/code-scanning/trivy.yml

  #     - name: Run zizmor
  #       uses: ./.github/actions/zizmor
  #       with:
  #         persona: pedantic

  #     - name: Run gitleaks
  #       uses: ./.github/actions/gitleaks
